using System;

namespace FaceRecognitionSample1.Models
{
    /// <summary>
    /// Represents the extracted face feature data tied to a specific engine version.
    /// This data is designed to be persisted in a database.
    /// </summary>
    public class FaceFeatureEntity
    {
        /// <summary>
        /// The version of the recognition engine used to extract this feature.
        /// </summary>
        public int EngineVersion { get; set; }

        /// <summary>
        /// The binary feature data generated by the engine.
        /// </summary>
        public byte[] FeatureData { get; set; } = Array.Empty<byte>();

        /// <summary>
        /// The timestamp when the feature was extracted.
        /// </summary>
        public DateTime ExtractedAt { get; set; }
    }
}