//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceRecognitionSample1.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FaceRecognitionSample1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   顔認識サンプル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザ管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnUserManagement {
            get {
                return ResourceManager.GetString("BtnUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カメラ映像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewTitle {
            get {
                return ResourceManager.GetString("CameraViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   判定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JudgmentLabel {
            get {
                return ResourceManager.GetString("JudgmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トリガー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指標一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Metrics {
            get {
                return ResourceManager.GetString("Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指標一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetricsTitle {
            get {
                return ResourceManager.GetString("MetricsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1:N に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeOneToMany {
            get {
                return ResourceManager.GetString("ModeOneToMany", resourceCulture);
            }
        }

        /// <summary>
        ///   照合方式
        /// </summary>
        public static string HeaderRecognitionMode {
            get {
                return ResourceManager.GetString("HeaderRecognitionMode", resourceCulture);
            }
        }

        /// <summary>
        ///   照合モード
        /// </summary>
        public static string HeaderTriggerMode {
            get {
                return ResourceManager.GetString("HeaderTriggerMode", resourceCulture);
            }
        }

        /// <summary>
        ///   照合対象ユーザ
        /// </summary>
        public static string HeaderTargetUser {
            get {
                return ResourceManager.GetString("HeaderTargetUser", resourceCulture);
            }
        }

        /// <summary>
        ///   ユーザ名でフィルタ
        /// </summary>
        public static string PlaceholderSearchUser {
            get {
                return ResourceManager.GetString("PlaceholderSearchUser", resourceCulture);
            }
        }

        /// <summary>
        ///   ユーザを選択してください
        /// </summary>
        public static string ComboDefaultSelectUser {
            get {
                return ResourceManager.GetString("ComboDefaultSelectUser", resourceCulture);
            }
        }

        /// <summary>
        ///   照合開始
        /// </summary>
        public static string BtnStartRecognition {
            get {
                return ResourceManager.GetString("BtnStartRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1:1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeOneToOne {
            get {
                return ResourceManager.GetString("ModeOneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリ画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryImage {
            get {
                return ResourceManager.GetString("QueryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank2 {
            get {
                return ResourceManager.GetString("Rank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank3 {
            get {
                return ResourceManager.GetString("Rank3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank4 {
            get {
                return ResourceManager.GetString("Rank4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank5 {
            get {
                return ResourceManager.GetString("Rank5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リアルタイム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Realtime {
            get {
                return ResourceManager.GetString("Realtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   照合方式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecognitionMode {
            get {
                return ResourceManager.GetString("RecognitionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   照合結果 (1:N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultTitleOneToMany {
            get {
                return ResourceManager.GetString("ResultTitleOneToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   照合結果 (1:1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultTitleOneToOne {
            get {
                return ResourceManager.GetString("ResultTitleOneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一致度 (スコア) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScoreLabel {
            get {
                return ResourceManager.GetString("ScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索キーワードを入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定画面を開きます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsOpenMessage {
            get {
                return ResourceManager.GetString("SettingsOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   照合開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecognition {
            get {
                return ResourceManager.GetString("StartRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusMatch {
            get {
                return ResourceManager.GetString("StatusMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusMismatch {
            get {
                return ResourceManager.GetString("StatusMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ターゲット画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetImage {
            get {
                return ResourceManager.GetString("TargetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   照合対象ユーザ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetUsersLabel {
            get {
                return ResourceManager.GetString("TargetUsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最も一致するターゲット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TopCandidateImage {
            get {
                return ResourceManager.GetString("TopCandidateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トリガー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TriggerManual {
            get {
                return ResourceManager.GetString("TriggerManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   照合モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TriggerMode {
            get {
                return ResourceManager.GetString("TriggerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リアルタイム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TriggerRealtime {
            get {
                return ResourceManager.GetString("TriggerRealtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザ管理画面を開きます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserManagementOpenMessage {
            get {
                return ResourceManager.GetString("UserManagementOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザ名でフィルタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserNameFilter {
            get {
                return ResourceManager.GetString("UserNameFilter", resourceCulture);
            }
        }
    }
}
